### ISSUE TITLE
Petting Zoo simple_spread example error

### ISSUE THREAD

**Issue by mlanas** [instadeepai/Mava#293]
# Problem
Error when executing _petting_zoo/mpe/simple_spread_ example ([run_maddpg.py](https://github.com/instadeepai/Mava/blob/7e6fd836f429212e101585847c494ef793840db7/examples/petting_zoo/mpe/simple_spread/feedforward/decentralised/run_maddpg.py)) on **develop** branch:
```bash
[executor/0] Traceback (most recent call last):
[executor/0]   File "/usr/local/lib/python3.6/dist-packages/launchpad/nodes/python/process_entry.py", line 93, in <module>
[executor/0]     app.run(main)
[executor/0]   File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 300, in run
[executor/0]     _run_main(main, args)
[executor/0]   File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
[executor/0]     sys.exit(main(argv))
[executor/0]   File "/usr/local/lib/python3.6/dist-packages/launchpad/nodes/python/process_entry.py", line 88, in main
[executor/0]     functions[task_id]()
[executor/0]   File "/usr/local/lib/python3.6/dist-packages/launchpad/nodes/python/node.py", line 72, in _construct_function
[executor/0]     return functools.partial(self._function, *args, **kwargs)()
[executor/0]   File "/usr/local/lib/python3.6/dist-packages/launchpad/nodes/courier/node.py", line 123, in run
[executor/0]     instance.run()
[executor/0]   File "/home/app/mava/mava/environment_loop.py", line 467, in run
[executor/0]     result = self.run_episode()
[executor/0]   File "/home/app/mava/mava/environment_loop.py", line 396, in run_episode
[executor/0]     actions, next_timestep=timestep, next_extras=env_extras
[executor/0]   File "/home/app/mava/mava/systems/tf/maddpg/execution.py", line 180, in observe
[executor/0]     self._adder.add(policy, next_timestep, next_extras)  # type: ignore
[executor/0]   File "/usr/local/lib/python3.6/dist-packages/acme/adders/reverb/transition.py", line 130, in add
[executor/0]     super().add(*args, **kwargs)
[executor/0]   File "/home/app/mava/mava/adders/reverb/base.py", line 180, in add
[executor/0]     self._write()
[executor/0]   File "/home/app/mava/mava/adders/reverb/transition.py", line 145, in _write
[executor/0]     get_last, (history["observations"], history["extras"])
[executor/0]   File "/usr/local/lib/python3.6/dist-packages/tree/__init__.py", line 510, in map_structure
[executor/0]     [func(*args) for args in zip(*map(flatten, structures))])
[executor/0]   File "/usr/local/lib/python3.6/dist-packages/tree/__init__.py", line 510, in <listcomp>
[executor/0]     [func(*args) for args in zip(*map(flatten, structures))])
[executor/0]   File "/home/app/mava/mava/adders/reverb/transition.py", line 130, in get_last
[executor/0]     return x[self._last_idx]
[executor/0]   File "/usr/local/lib/python3.6/dist-packages/reverb/trajectory_writer.py", line 590, in __getitem__
[executor/0]     path=path)
[executor/0]   File "/usr/local/lib/python3.6/dist-packages/reverb/trajectory_writer.py", line 616, in __init__
[executor/0]     raise ValueError('TrajectoryColumns cannot contain any None data '
[executor/0] ValueError: TrajectoryColumns cannot contain any None data references, got [None] for TrajectoryColumn at path ('observations', 'agent_0', 'observation', 26)
```
# Execution
The example was executed using docker.

After cloning the repo I followed the installation guide and executed the following commands:
```bash
make build
make run EXAMPLE=examples/petting_zoo/mpe/simple_spread/feedforward/decentralised/run_maddpg.py 
```

# Note
During the execution of the ```make build``` command, the following errors were encountered:
```bash
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pysc2 3.0.0 requires enum34, which is not installed.

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
open-spiel 0.3.1 requires tensorflow==2.4.1, but you have tensorflow 2.5.0 which is incompatible.
open-spiel 0.3.1 requires tensorflow-probability<0.8.0,>=0.7.0, but you have tensorflow-probability 0.12.2 which is incompatible.
flatland-rl 2.2.2 requires gym==0.14.0, but you have gym 0.18.3 which is incompatible.
flatland-rl 2.2.2 requires pytest<5,>=3.8.2, but you have pytest 6.2.4 which is incompatible.
```

Despite these errors, the debugging env example ([run_maddpg.py](https://github.com/instadeepai/Mava/blob/7e6fd836f429212e101585847c494ef793840db7/examples/debugging/simple_spread/feedforward/decentralised/run_maddpg.py)) does runs and trains correctly.

**Comment by KaleabTessera** [comment]
Hi @mlanas , thanks for pointing this out! We are in the process of fixing this and should have a fix out soon.

**Comment by KaleabTessera** [comment]
Hi @mlanas , can you please check if this problem still exists? We introduced a fix that we think should fix this.

**Comment by mlanas** [comment]
@KaleabTessera Looks good, thanks for the fix :)
