### ISSUE TITLE
Bug while running the robocup enviroment

### ISSUE THREAD

**Issue by Pvcunha** [instadeepai/Mava#329]
Hi guys!
I'm trying to run your  `run_mad4pg.py` script from the robocup examples but it's not working for me. I'm using a ubuntu 20.04 with a python 3.7. Here's the command I used to run
```python examples/robocup/recurrent/state_based/run_mad4pg.py```. 

And I will attach here the error returned, thank you all in advance!
```2021-11-11 18:06:33.030655: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/pedro/anaconda3/envs/mava/lib/python3.7/site-packages/cv2/../../lib64:/home/pedro/anaconda3/envs/mava/lib
2021-11-11 18:06:33.030679: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-11-11 18:06:36.869296: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/pedro/anaconda3/envs/mava/lib/python3.7/site-packages/cv2/../../lib64:/home/pedro/anaconda3/envs/mava/lib
2021-11-11 18:06:36.869371: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2021-11-11 18:06:36.869428: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (pedro-All-Series): /proc/driver/nvidia/version does not exist
Traceback (most recent call last):
  File "examples/robocup/recurrent/state_based/run_mad4pg.py", line 24, in <module>
    from mava.systems.tf import mad4pg
  File "/home/pedro/anaconda3/envs/mava/lib/python3.7/site-packages/mava/systems/tf/mad4pg/__init__.py", line 16, in <module>
    from mava.systems.tf.mad4pg.execution import (
  File "/home/pedro/anaconda3/envs/mava/lib/python3.7/site-packages/mava/systems/tf/mad4pg/execution.py", line 25, in <module>
    from mava.systems.tf.maddpg.execution import (
  File "/home/pedro/anaconda3/envs/mava/lib/python3.7/site-packages/mava/systems/tf/maddpg/__init__.py", line 21, in <module>
    from mava.systems.tf.maddpg.system import MADDPG
  File "/home/pedro/anaconda3/envs/mava/lib/python3.7/site-packages/mava/systems/tf/maddpg/system.py", line 37, in <module>
    from mava.systems.tf.maddpg import builder, training
  File "/home/pedro/anaconda3/envs/mava/lib/python3.7/site-packages/mava/systems/tf/maddpg/builder.py", line 35, in <module>
    from mava.wrappers import DetailedTrainerStatistics
  File "/home/pedro/anaconda3/envs/mava/lib/python3.7/site-packages/mava/wrappers/__init__.py", line 16, in <module>
    from mava.wrappers.debugging_envs import DebuggingEnvWrapper, TwoStepWrapper
  File "/home/pedro/anaconda3/envs/mava/lib/python3.7/site-packages/mava/wrappers/debugging_envs.py", line 30, in <module>
    from mava.wrappers.pettingzoo import PettingZooParallelEnvWrapper
  File "/home/pedro/anaconda3/envs/mava/lib/python3.7/site-packages/mava/wrappers/pettingzoo.py", line 26, in <module>
    from supersuit import black_death_v1
  File "/home/pedro/anaconda3/envs/mava/lib/python3.7/site-packages/supersuit/__init__.py", line 1, in <module>
    from .generic_wrappers import * # NOQA
  File "/home/pedro/anaconda3/envs/mava/lib/python3.7/site-packages/supersuit/generic_wrappers/__init__.py", line 1, in <module>
    from .frame_skip import frame_skip_v0 # NOQA
  File "/home/pedro/anaconda3/envs/mava/lib/python3.7/site-packages/supersuit/generic_wrappers/frame_skip.py", line 3, in <module>
    from pettingzoo.utils.wrappers import BaseWrapper, BaseParallelWraper
ImportError: cannot import name 'BaseParallelWraper' from 'pettingzoo.utils.wrappers' (/home/pedro/anaconda3/envs/mava/lib/python3.7/site-packages/pettingzoo/utils/wrappers/__init__.py)```

**Comment by DriesSmit** [comment]
Hey @Pvcunha :) Let's try and get you up and running. After building Mava did you also run the RoboCup builder?

Step 1: `make build`
Step 2: `make build_robocup`

Let me know if it works.

**Comment by mmorris44** [comment]
Hey @Pvcunha, please also check whether the other examples run or not (one of the debugging examples would be great, e.g. examples/debugging/simple_spread/feedforward/centralised/run_mad4pg.py). If you're trying to run outside of docker, something probably went wrong during your installation of the Mava dependencies.

**Comment by Pvcunha** [comment]
Hi @DriesSmit yeah I did it, after thoose commands I tried to run the robocup example and then I got that error :(

**Comment by Pvcunha** [comment]
Hello @mmorris44, I tried outside docker in a conda env. I will try to install again later this week and then I come back to you guys with an update, Thanks!

**Comment by DriesSmit** [comment]
Hey @Pvcunha :) I think I found wat was wrong. See this [PR](https://github.com/instadeepai/Mava/pull/334). Let me know if it is working now.
