### ISSUE TITLE
ValueError: Expected floating point type, got <dtype: 'int64'>

### ISSUE THREAD

**Issue by MichaelClasby0** [instadeepai/Mava#335]
Hi there, 
We are trying to integrate Mava into our project, with a custom pettingzoo parallel environment wrapped in your `PettingZooParallelEnvWrapper` and we are facing this issue.
We used the code provided in your usage section to integrate and cannot seem to find the source of the below problem. 
The stack trace also appears with `executor`, `evaluator` and others in place of trainer.

I am not sure if you might have seen this before, or what else might be useful to locate the issue, please advise.

```
[trainer/0] I1128 22:36:26.525356 139693398167488 node.py:62] Reverb client connecting to: localhost:18746
[trainer/0] Traceback (most recent call last):
[trainer/0]   File "/home/NAME/.cache/pypoetry/virtualenvs/ai-market-contest-UVc7OfEw-py3.9/lib/python3.9/site-packages/launchpad/nodes/python/process_entry.py", line 110, in <module>
[trainer/0]     app.run(main)
[trainer/0]   File "/home/NAME/.cache/pypoetry/virtualenvs/ai-market-contest-UVc7OfEw-py3.9/lib/python3.9/site-packages/absl/app.py", line 312, in run
[trainer/0]     _run_main(main, args)
[trainer/0]   File "/home/NAME/.cache/pypoetry/virtualenvs/ai-market-contest-UVc7OfEw-py3.9/lib/python3.9/site-packages/absl/app.py", line 258, in _run_main
[trainer/0]     sys.exit(main(argv))
[trainer/0]   File "/home/NAME/.cache/pypoetry/virtualenvs/ai-market-contest-UVc7OfEw-py3.9/lib/python3.9/site-packages/launchpad/nodes/python/process_entry.py", line 105, in main
[trainer/0]     functions[task_id]()
[trainer/0]   File "/home/NAME/.cache/pypoetry/virtualenvs/ai-market-contest-UVc7OfEw-py3.9/lib/python3.9/site-packages/launchpad/nodes/python/node.py", line 72, in _construct_function
[trainer/0]     return functools.partial(self._function, *args, **kwargs)()
[trainer/0]   File "/home/NAME/.cache/pypoetry/virtualenvs/ai-market-contest-UVc7OfEw-py3.9/lib/python3.9/site-packages/launchpad/nodes/courier/node.py", line 107, in run
[trainer/0]     instance = self._construct_instance()  # pytype:disable=wrong-arg-types
[trainer/0]   File "/home/NAME/.cache/pypoetry/virtualenvs/ai-market-contest-UVc7OfEw-py3.9/lib/python3.9/site-packages/launchpad/nodes/python/node.py", line 177, in _construct_instance
[trainer/0]     self._instance = self._constructor(*args, **kwargs)
[trainer/0]   File "/home/NAME/.cache/pypoetry/virtualenvs/ai-market-contest-UVc7OfEw-py3.9/lib/python3.9/site-packages/mava/systems/tf/madqn/system.py", line 414, in trainer
[trainer/0]     system_networks = architecture.create_system()
[trainer/0]   File "/home/NAME/.cache/pypoetry/virtualenvs/ai-market-contest-UVc7OfEw-py3.9/lib/python3.9/site-packages/mava/components/tf/architectures/decentralised.py", line 98, in create_system
[trainer/0]     networks = self.create_actor_variables()
[trainer/0]   File "/home/NAME/.cache/pypoetry/virtualenvs/ai-market-contest-UVc7OfEw-py3.9/lib/python3.9/site-packages/mava/components/tf/architectures/decentralised.py", line 83, in create_actor_variables
[trainer/0]     tf2_utils.create_variables(self._value_networks[agent_net_key], [obs_spec])
[trainer/0]   File "/home/NAME/.cache/pypoetry/virtualenvs/ai-market-contest-UVc7OfEw-py3.9/lib/python3.9/site-packages/acme/tf/utils.py", line 103, in create_variables
[trainer/0]     dummy_output = network(*add_batch_dim(dummy_input))
[trainer/0]   File "/home/NAME/.cache/pypoetry/virtualenvs/ai-market-contest-UVc7OfEw-py3.9/lib/python3.9/site-packages/sonnet/src/utils.py", line 89, in _decorate_unbound_method
[trainer/0]     return decorator_fn(bound_method, self, args, kwargs)
[trainer/0]   File "/home/NAME/.cache/pypoetry/virtualenvs/ai-market-contest-UVc7OfEw-py3.9/lib/python3.9/site-packages/sonnet/src/base.py", line 272, in wrap_with_name_scope
[trainer/0]     return method(*args, **kwargs)
[trainer/0]   File "/home/NAME/.cache/pypoetry/virtualenvs/ai-market-contest-UVc7OfEw-py3.9/lib/python3.9/site-packages/sonnet/src/sequential.py", line 72, in __call__
[trainer/0]     outputs = mod(outputs, *args, **kwargs)
[trainer/0]   File "/home/NAME/.cache/pypoetry/virtualenvs/ai-market-contest-UVc7OfEw-py3.9/lib/python3.9/site-packages/sonnet/src/utils.py", line 89, in _decorate_unbound_method
[trainer/0]     return decorator_fn(bound_method, self, args, kwargs)
[trainer/0]   File "/home/NAME/.cache/pypoetry/virtualenvs/ai-market-contest-UVc7OfEw-py3.9/lib/python3.9/site-packages/sonnet/src/base.py", line 272, in wrap_with_name_scope
[trainer/0]     return method(*args, **kwargs)
[trainer/0]   File "/home/NAME/.cache/pypoetry/virtualenvs/ai-market-contest-UVc7OfEw-py3.9/lib/python3.9/site-packages/mava/components/tf/networks/continuous.py", line 117, in __call__
[trainer/0]     return self._network(tf2_utils.batch_concat(observations))
[trainer/0]   File "/home/NAME/.cache/pypoetry/virtualenvs/ai-market-contest-UVc7OfEw-py3.9/lib/python3.9/site-packages/sonnet/src/utils.py", line 89, in _decorate_unbound_method
[trainer/0]     return decorator_fn(bound_method, self, args, kwargs)
[trainer/0]   File "/home/NAME/.cache/pypoetry/virtualenvs/ai-market-contest-UVc7OfEw-py3.9/lib/python3.9/site-packages/sonnet/src/base.py", line 272, in wrap_with_name_scope
[trainer/0]     return method(*args, **kwargs)
[trainer/0]   File "/home/NAME/.cache/pypoetry/virtualenvs/ai-market-contest-UVc7OfEw-py3.9/lib/python3.9/site-packages/sonnet/src/sequential.py", line 72, in __call__
[trainer/0]     outputs = mod(outputs, *args, **kwargs)
[trainer/0]   File "/home/NAME/.cache/pypoetry/virtualenvs/ai-market-contest-UVc7OfEw-py3.9/lib/python3.9/site-packages/sonnet/src/utils.py", line 89, in _decorate_unbound_method
[trainer/0]     return decorator_fn(bound_method, self, args, kwargs)
[trainer/0]   File "/home/NAME/.cache/pypoetry/virtualenvs/ai-market-contest-UVc7OfEw-py3.9/lib/python3.9/site-packages/sonnet/src/base.py", line 272, in wrap_with_name_scope
[trainer/0]     return method(*args, **kwargs)
[trainer/0]   File "/home/NAME/.cache/pypoetry/virtualenvs/ai-market-contest-UVc7OfEw-py3.9/lib/python3.9/site-packages/sonnet/src/linear.py", line 89, in __call__
[trainer/0]     self._initialize(inputs)
[trainer/0]   File "/home/NAME/.cache/pypoetry/virtualenvs/ai-market-contest-UVc7OfEw-py3.9/lib/python3.9/site-packages/sonnet/src/utils.py", line 89, in _decorate_unbound_method
[trainer/0]     return decorator_fn(bound_method, self, args, kwargs)
[trainer/0]   File "/home/NAME/.cache/pypoetry/virtualenvs/ai-market-contest-UVc7OfEw-py3.9/lib/python3.9/site-packages/sonnet/src/once.py", line 93, in wrapper
[trainer/0]     _check_no_output(wrapped(*args, **kwargs))
[trainer/0]   File "/home/NAME/.cache/pypoetry/virtualenvs/ai-market-contest-UVc7OfEw-py3.9/lib/python3.9/site-packages/sonnet/src/utils.py", line 89, in _decorate_unbound_method
[trainer/0]     return decorator_fn(bound_method, self, args, kwargs)
[trainer/0]   File "/home/NAME/.cache/pypoetry/virtualenvs/ai-market-contest-UVc7OfEw-py3.9/lib/python3.9/site-packages/sonnet/src/base.py", line 272, in wrap_with_name_scope
[trainer/0]     return method(*args, **kwargs)
[trainer/0]   File "/home/NAME/.cache/pypoetry/virtualenvs/ai-market-contest-UVc7OfEw-py3.9/lib/python3.9/site-packages/sonnet/src/linear.py", line 81, in _initialize
[trainer/0]     self.w_init([self.input_size, self.output_size], inputs.dtype),
[trainer/0]   File "/home/NAME/.cache/pypoetry/virtualenvs/ai-market-contest-UVc7OfEw-py3.9/lib/python3.9/site-packages/keras/initializers/initializers_v2.py", line 514, in __call__
[trainer/0]     dtype = _assert_float_dtype(_get_dtype(dtype))
[trainer/0]   File "/home/NAME/.cache/pypoetry/virtualenvs/ai-market-contest-UVc7OfEw-py3.9/lib/python3.9/site-packages/keras/initializers/initializers_v2.py", line 968, in _assert_float_dtype
[trainer/0]     raise ValueError(f'Expected floating point type, got {dtype}.')
[trainer/0] ValueError: Expected floating point type, got <dtype: 'int64'>.
```

Thanks in advance

**Comment by KaleabTessera** [comment]
Hi @MichaelClasby0 , it looks like something in your observation spec is `int64`. Can you try converting it to float32?

**Comment by jkterry1** [comment]
Hey, I'm the maintainer of pettingzoo and just saw this on accident. You can just use the dtype wrapper in supersuit for this- https://github.com/Farama-Foundation/SuperSuit

**Comment by KaleabTessera** [comment]
Thanks @jkterry1 :open_hands: 

@MichaelClasby0 Here is an example of using the `dtype` wrapper in mava - https://github.com/instadeepai/Mava/blob/8c4cee233ac9a8186f356a3c2f01a17f95253a08/mava/utils/environments/pettingzoo_utils.py#L87 .

Please re-open this issue, if your problem is not solved.
