### ISSUE TITLE
ValueError: Unable to create item in table 'priority_table' since the provided trajectory is inconsistent

### ISSUE THREAD

**Issue by vanpra** [instadeepai/Mava#340]
Hi again, thanks for helping out with my previous issue. I'm still trying to get a custom parallel pettingzoo environment to work with but I currently get the error below. The `step` method of our custom environment seems to be called but I'm not sure if training is actually occurring as I can't get any logs for tensorboard.

```
[executor/0] Traceback (most recent call last):
[executor/0]   File "/home/{name}/.cache/pypoetry/virtualenvs/ai-market-contest-RFU3MKa2-py3.9/lib/python3.9/site-packages/launchpad/nodes/python/process_entry.py", line 110, in <module>
[executor/0]     app.run(main)
[executor/0]   File "/home/{name}/.cache/pypoetry/virtualenvs/ai-market-contest-RFU3MKa2-py3.9/lib/python3.9/site-packages/absl/app.py", line 312, in run
[executor/0]     _run_main(main, args)
[executor/0]   File "/home/{name}/.cache/pypoetry/virtualenvs/ai-market-contest-RFU3MKa2-py3.9/lib/python3.9/site-packages/absl/app.py", line 258, in _run_main
[executor/0]     sys.exit(main(argv))
[executor/0]   File "/home/{name}/.cache/pypoetry/virtualenvs/ai-market-contest-RFU3MKa2-py3.9/lib/python3.9/site-packages/launchpad/nodes/python/process_entry.py", line 105, in main
[executor/0]     functions[task_id]()
[executor/0]   File "/home/{name}/.cache/pypoetry/virtualenvs/ai-market-contest-RFU3MKa2-py3.9/lib/python3.9/site-packages/launchpad/nodes/python/node.py", line 72, in _construct_function
[executor/0]     return functools.partial(self._function, *args, **kwargs)()
[executor/0]   File "/home/{name}/.cache/pypoetry/virtualenvs/ai-market-contest-RFU3MKa2-py3.9/lib/python3.9/site-packages/launchpad/nodes/courier/node.py", line 124, in run
[executor/0]     instance.run()
[executor/0]   File "/home/{name}/.cache/pypoetry/virtualenvs/ai-market-contest-RFU3MKa2-py3.9/lib/python3.9/site-packages/mava/environment_loop.py", line 538, in run
[executor/0]     result = self.run_episode()
[executor/0]   File "/home/{name}/.cache/pypoetry/virtualenvs/ai-market-contest-RFU3MKa2-py3.9/lib/python3.9/site-packages/mava/environment_loop.py", line 435, in run_episode
[executor/0]     self._executor.observe(
[executor/0]   File "/home/{name}/.cache/pypoetry/virtualenvs/ai-market-contest-RFU3MKa2-py3.9/lib/python3.9/site-packages/mava/systems/tf/madqn/execution.py", line 267, in observe
[executor/0]     self._adder.add(actions, next_timestep, next_extras)
[executor/0]   File "/home/{name}/.cache/pypoetry/virtualenvs/ai-market-contest-RFU3MKa2-py3.9/lib/python3.9/site-packages/acme/adders/reverb/transition.py", line 134, in add
[executor/0]     super().add(*args, **kwargs)
[executor/0]   File "/home/{name}/.cache/pypoetry/virtualenvs/ai-market-contest-RFU3MKa2-py3.9/lib/python3.9/site-packages/mava/adders/reverb/base.py", line 426, in add
[executor/0]     self._write()
[executor/0]   File "/home/{name}/.cache/pypoetry/virtualenvs/ai-market-contest-RFU3MKa2-py3.9/lib/python3.9/site-packages/mava/adders/reverb/transition.py", line 207, in _write
[executor/0]     self.write_experience_to_tables(transition, table_priorities)
[executor/0]   File "/home/{name}/.cache/pypoetry/virtualenvs/ai-market-contest-RFU3MKa2-py3.9/lib/python3.9/site-packages/mava/adders/reverb/base.py", line 356, in write_experience_to_tables
[executor/0]     self._writer.create_item(
[executor/0]   File "/home/{name}/.cache/pypoetry/virtualenvs/ai-market-contest-RFU3MKa2-py3.9/lib/python3.9/site-packages/reverb/trajectory_writer.py", line 352, in create_item
[executor/0]     self._writer.CreateItem(table, priority,
[executor/0] ValueError: Unable to create item in table 'priority_table' since the provided trajectory is inconsistent with the table signature. The table expects column 0 to be a float [] tensor but got a double [] tensor.
[executor/0] 
[executor/0] The table signature is:
[executor/0]    0: Tensor<name: 'observations/player_0/observation/observations/player_0/observation', dtype: float, shape: []>, 1: Tensor<name: 'observations/player_0/legal_actions/observations/player_0/legal_actions', dtype: int64, shape: []>, 2: Tensor<name: 'observations/player_0/terminal/observations/player_0/terminal', dtype: float, shape: [1]>, 3: Tensor<name: 'observations/player_1/observation/observations/player_1/observation', dtype: float, shape: []>, 4: Tensor<name: 'observations/player_1/legal_actions/observations/player_1/legal_actions', dtype: int64, shape: []>, 5: Tensor<name: 'observations/player_1/terminal/observations/player_1/terminal', dtype: float, shape: [1]>, 6: Tensor<name: 'actions/player_0/actions/player_0', dtype: int64, shape: []>, 7: Tensor<name: 'actions/player_1/actions/player_1', dtype: int64, shape: []>, 8: Tensor<name: 'rewards/player_0/rewards/player_0', dtype: float, shape: []>, 9: Tensor<name: 'rewards/player_1/rewards/player_1', dtype: float, shape: []>, 10: Tensor<name: 'discounts/player_0/discounts/player_0', dtype: float, shape: []>, 11: Tensor<name: 'discounts/player_1/discounts/player_1', dtype: float, shape: []>, 12: Tensor<name: 'next_observations/player_0/observation/next_observations/player_0/observation', dtype: float, shape: []>, 13: Tensor<name: 'next_observations/player_0/legal_actions/next_observations/player_0/legal_actions', dtype: int64, shape: []>, 14: Tensor<name: 'next_observations/player_0/terminal/next_observations/player_0/terminal', dtype: float, shape: [1]>, 15: Tensor<name: 'next_observations/player_1/observation/next_observations/player_1/observation', dtype: float, shape: []>, 16: Tensor<name: 'next_observations/player_1/legal_actions/next_observations/player_1/legal_actions', dtype: int64, shape: []>, 17: Tensor<name: 'next_observations/player_1/terminal/next_observations/player_1/terminal', dtype: float, shape: [1]>
[executor/0] 
[executor/0] The provided trajectory signature is:
[executor/0]    0: Tensor<name: '0', dtype: double, shape: []>, 1: Tensor<name: '1', dtype: int64, shape: []>, 2: Tensor<name: '2', dtype: float, shape: [1]>, 3: Tensor<name: '3', dtype: double, shape: []>, 4: Tensor<name: '4', dtype: int64, shape: []>, 5: Tensor<name: '5', dtype: float, shape: [1]>, 6: Tensor<name: '6', dtype: int64, shape: []>, 7: Tensor<name: '7', dtype: int64, shape: []>, 8: Tensor<name: '8', dtype: float, shape: []>, 9: Tensor<name: '9', dtype: float, shape: []>, 10: Tensor<name: '10', dtype: float, shape: []>, 11: Tensor<name: '11', dtype: float, shape: []>, 12: Tensor<name: '12', dtype: double, shape: []>, 13: Tensor<name: '13', dtype: int64, shape: []>, 14: Tensor<name: '14', dtype: float, shape: [1]>, 15: Tensor<name: '15', dtype: double, shape: []>, 16: Tensor<name: '16', dtype: int64, shape: []>, 17: Tensor<name: '17', dtype: float, shape: [1]>.
[executor/0] 
```

**Comment by KaleabTessera** [comment]
Hi @vanpra , looks like a mismatch in the type of your observation. The table signature says it is a float, but you are adding doubles. Please check that the observation types are consistent between your spec and what you get from the env/add to replay.

**Comment by KaleabTessera** [comment]
Hi @vanpra , please see proposed solution here - https://github.com/instadeepai/Mava/issues/335 . If that doesn't work, please re-open this issue.
