### ISSUE TITLE
AttributeError: 'OLT' object has no attribute 'items'

### ISSUE THREAD

**Issue by xavierwwj** [instadeepai/Mava#451]
Hi,

I am using the latest docker image 'instadeepct/mava:pz-latest'. I am trying to run maddpg on my own custom environment, but I encountered the following problem AttributeError: 'OLT' object has no attribute 'items' below. I then tried to do the same but on pettingzoo/classic/connect_four_v3.py though I encountered the same problem. The flags I specified are below. I noticed that the current environments that are working for me are the parallel environment types. Could this be a problem because I'm using sequential, where <wrapper>._convert_observations() returns an OLT instead of a Dict[str, types.OLT]?

run_maddpg.py:
```
FLAGS = flags.FLAGS

flags.DEFINE_string(
    "env_class",
    "classic",
    "Pettingzoo environment class, e.g. atari (str).",
)
flags.DEFINE_string(
    "env_type",
    "sequential",
    "Pettingzoo environment type.",
)
flags.DEFINE_string(
    "env_name",
    "connect_four_v3",
    "Pettingzoo environment name, e.g. pong (str).",
)
flags.DEFINE_string(
    "mava_id",
    str(datetime.now()),
    "Experiment identifier that can be used to continue experiments.",
)
flags.DEFINE_string("base_dir", "/home/app/mava/logs/", "Base dir to store experiments.")
```

Error:
```
[evaluator/0]
[evaluator/0] Traceback (most recent call last):
[evaluator/0]   File "/mava/lib/python3.8/site-packages/launchpad/nodes/python/process_entry.py", line 110, in <module>
[evaluator/0]     app.run(main)
[evaluator/0]   File "/mava/lib/python3.8/site-packages/absl/app.py", line 312, in run
[evaluator/0]     _run_main(main, args)
[evaluator/0]   File "/mava/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
[evaluator/0]     sys.exit(main(argv))
[evaluator/0]   File "/mava/lib/python3.8/site-packages/launchpad/nodes/python/process_entry.py", line 105, in main
[evaluator/0]     functions[task_id]()
[evaluator/0]   File "/mava/lib/python3.8/site-packages/launchpad/nodes/python/node.py", line 72, in _construct_function
[evaluator/0]     return functools.partial(self._function, *args, **kwargs)()
[evaluator/0]   File "/mava/lib/python3.8/site-packages/launchpad/nodes/courier/node.py", line 124, in run
[evaluator/0]     instance.run()
[evaluator/0]   File "/home/app/mava/mava/environment_loop.py", line 582, in run
[evaluator/0]     result = self.run_episode()
[evaluator/0]   File "/home/app/mava/mava/environment_loop.py", line 447, in run_episode
[evaluator/0]     actions = self._get_actions(timestep)
[evaluator/0]   File "/home/app/mava/mava/environment_loop.py", line 362, in _get_actions
[evaluator/0]     return self._executor.select_actions(timestep.observation)
[evaluator/0]   File "/home/app/mava/mava/systems/tf/maddpg/execution.py", line 171, in select_actions
[evaluator/0]     for agent, observation in observations.items():
[evaluator/0] AttributeError: 'OLT' object has no attribute 'items'
```

**Comment by KaleabTessera** [comment]
Hi @xavierwwj , it looks like your `timestep.observation` is an OLT object as follows:
```
timestep = OLT(
                observation=OLT(...),
                legal_actions=...,
                terminal=...,
            )
```
, when it should be: 
```
timestep = OLT(
                observation={'agent_0':...},
                legal_actions=...,
                terminal=...,
            )
```
This is likely being returned by your environment's step function.

**Comment by KaleabTessera** [comment]
@xavierwwj So you need to use `PettingZooParallelEnvWrapper` with the `ParallelEnvironmentLoop`. In your example, looks like you are using  `PettingZooAECEnvWrapper` (sequential wrapper) with the `ParallelEnvironmentLoop` (parallel loop). 

Is your environment parallel or sequential? If it is parallel, I recommend using  `ParallelEnvironmentLoop`.
