### ISSUE TITLE
[reverb/pybind.cc:447] Tensor can't be extracted from the source represented as ndarray: INTERNAL: Unsupported object type DiscreteArray

### ISSUE THREAD

**Issue by MohibAzam** [instadeepai/Mava#468]
Hi, I'm trying to get Mava to run on a custom environment of ours. I've written a wrapper for it but I've been having some issues in getting it to work properly. I'm using the Decentralized MAPPO implementation for this. The traceback I'm currently dealing with is:

```
[executor/0] [reverb/pybind.cc:447] Tensor can't be extracted from the source represented as ndarray: INTERNAL: Unsupported object type DiscreteArray
[executor/0] Traceback (most recent call last):
[executor/0]   File "/home/mohib/anaconda3/lib/python3.9/site-packages/launchpad/nodes/python/process_entry.py", line 110, in <module>
[executor/0]     app.run(main)
[executor/0]   File "/home/mohib/anaconda3/lib/python3.9/site-packages/absl/app.py", line 312, in run
[executor/0]     _run_main(main, args)
[executor/0]   File "/home/mohib/anaconda3/lib/python3.9/site-packages/absl/app.py", line 258, in _run_main
[executor/0]     sys.exit(main(argv))
[executor/0]   File "/home/mohib/anaconda3/lib/python3.9/site-packages/launchpad/nodes/python/process_entry.py", line 105, in main
[executor/0]     functions[task_id]()
[executor/0]   File "/home/mohib/anaconda3/lib/python3.9/site-packages/launchpad/nodes/python/node.py", line 72, in _construct_function
[executor/0]     return functools.partial(self._function, *args, **kwargs)()
[executor/0]   File "/home/mohib/anaconda3/lib/python3.9/site-packages/launchpad/nodes/courier/node.py", line 124, in run
[executor/0]     instance.run()
[executor/0]   File "/home/mohib/anaconda3/lib/python3.9/site-packages/mava/environment_loop.py", line 582, in run
[executor/0]     result = self.run_episode()
[executor/0]   File "/home/mohib/anaconda3/lib/python3.9/site-packages/mava/environment_loop.py", line 433, in run_episode
[executor/0]     self._executor.observe_first(timestep, extras=env_extras)
[executor/0]   File "/home/mohib/anaconda3/lib/python3.9/site-packages/mava/systems/tf/mappo/execution.py", line 173, in observe_first
[executor/0]     self._adder.add_first(timestep)
[executor/0]   File "/home/mohib/anaconda3/lib/python3.9/site-packages/mava/adders/reverb/base.py", line 387, in add_first
[executor/0]     self._writer.append(
[executor/0]   File "/home/mohib/anaconda3/lib/python3.9/site-packages/reverb/trajectory_writer.py", line 301, in append
[executor/0]     flat_column_data_references = self._writer.AppendPartial(flat_column_data)
[executor/0] TypeError: AppendPartial(): incompatible function arguments. The following argument types are supported:
[executor/0]     1. (self: reverb.libpybind.TrajectoryWriter, arg0: List[Optional[tensorflow::Tensor]]) -> List[Optional[reverb.libpybind.WeakCellRef]]
```

The error would suggest that I need the observations need to be in the form of a pure TF Tensor, but I can't do that since earlier parts of the code require agent observations to be encased in an OLT. If I directly replace each observations[agent] with our environment's state as a Tensor, I'd get a traceback like this:
```
[executor/0] AttributeError: in user code:
[executor/0]
[executor/0]     File "/home/mohib/anaconda3/lib/python3.9/site-packages/mava/systems/tf/mappo/execution.py", line 134, in _select_actions  *
[executor/0]         log_prob, action = self._policy(agent, observation)
[executor/0]     File "/home/mohib/anaconda3/lib/python3.9/site-packages/mava/systems/tf/mappo/execution.py", line 94, in _policy  *
[executor/0]         observation = tf2_utils.add_batch_dim(observation_olt.observation)
[executor/0]
[executor/0]     AttributeError: 'Tensor' object has no attribute 'observation'
```

Any ideas on how to fix this? Our wrapper currently looks like this:
```
class ILocusEnv(dm_env.Environment):
    def __init__(self, size_r=5, size_c=5, driver_sim=Drivers(), gamma=0.56, objective=None):
        self.action_space = None
        self.observation_space = None
        self.reward_range = None
        self.size_r = size_r
        self.size_c = size_c
        self.gamma = gamma
        self.env = Environment(driver_sim, (self.size_r, self.size_c), objective)
        self.action_queue = [] 
        self.curr_obs = None

        agent_list = []
        for i in range(size_r * size_c):
            agent_list.append("agent_" + str(i))
        self.possible_agents = agent_list

    def step(self, action):
        # First, add the action to our queue
        self.action_queue.append(action + 1)

        # Next, check if our queue has a submitted action for every single agent
        if len(self.action_queue) == (self.size_r * self.size_c):
            # If so, assemble all the actions into a size_r * size_c array
            action_arr = np.empty((self.size_r, self.size_c))
            for r in range(self.size_r):
                for c in range(self.size_c):
                    action_arr[r, c] = self.action_queue[(r * self.size_c) + c] 

            # Submit this action to the environment, then reset the queue
            state, reward, term = self.env.step(action_arr)
            self.action_queue = []
            self.curr_obs = tf.convert_to_tensor(state)
            

            # Make sure to return it as a timestep!
            if term:
                step_type = dm_env.StepType.LAST
            else:
                step_type = dm_env.StepType.MID
            rewards = {}
            observations = {}
            gammas = {}
            for agent in self.possible_agents:
                rewards[agent] = tf.convert_to_tensor(reward)
                observations[agent] = types.OLT(
                    observation = self.curr_obs,
                    legal_actions = self.action_spec()[agent],
                    terminal = np.array(term)
                )
                gammas[agent] = tf.convert_to_tensor(self.gamma)
            return dm_env.TimeStep(
                observation=observations,
                reward=rewards,
                discount=gammas,
                step_type=step_type,
            )
        else:
            rewards = {}
            observations = {}
            gammas = {}
            for agent in self.possible_agents:
                rewards[agent] = tf.convert_to_tensor(0.0)
                observations[agent] = types.OLT(
                    observation = self.curr_obs,
                    legal_actions = self.action_spec()[agent],
                    terminal = np.array(False)
                )
                gammas[agent] = tf.convert_to_tensor(self.gamma)
            return dm_env.TimeStep(
                observation=observations,
                reward=rewards,
                discount=gammas,
                step_type=dm_env.StepType.MID,
            )
                

    def reset(self):
        self.curr_obs = tf.convert_to_tensor(self.env.reset(None))
        rewards = {}
        observations = {}
        gammas = {}
        for agent in self.possible_agents:
            rewards[agent] = tf.convert_to_tensor(np.array(0.0))
            observations[agent] = types.OLT(
                observation = self.curr_obs,
                legal_actions = self.action_spec()[agent],
                terminal = np.array(False)
            )
            gammas[agent] = tf.convert_to_tensor(np.array(self.gamma))
        return dm_env.TimeStep(
            observation=observations,
            reward=rewards,
            discount=gammas,
            step_type=dm_env.StepType.FIRST,
        )

    def action_spec(self) -> specs.DiscreteArray:
        action_spec_dict = {}
        for agent in self.possible_agents:
            action_spec_dict[agent] = specs.DiscreteArray(5)
        return action_spec_dict

    def observation_spec(self) -> specs.Array:
        obs_spec_dict = {}
        for agent in self.possible_agents:
            obs_spec_dict[agent] = types.OLT(
                observation = specs.Array(shape=[self.size_r, self.size_c],
                                          dtype=np.float),
                legal_actions = self.action_spec()[agent],
                terminal = specs.Array(shape=(1,), dtype=np.bool_),
            )
            # print(agent)
        return obs_spec_dict

    def reward_spec(self):
        # Based on the _environment code of dm_env on Github
        reward_spec_dict = {}
        for agent in self.possible_agents:
            reward_spec_dict[agent] = specs.Array(shape=(1,), dtype=float, name='reward')
        return reward_spec_dict

    def discount_spec(self):
        # Based on the _environment code of dm_env on Github
        dis_spec_dict = {}
        for agent in self.possible_agents:
            dis_spec_dict[agent] = specs.BoundedArray(shape=(1,), dtype=float, minimum=0., maximum=1., name='discount')
        return dis_spec_dict

    def extra_spec(self):
        ex_spec_dict = {}
        return ex_spec_dict
```

**Comment by KaleabTessera** [comment]
Hi @MohibAzam , thanks for your detailed issue. 

Can you print a sample of your `state` and `self.curr_obs`? It can be a valid numpy array or tensor. Also, can you print the observations that get passed in your reset? This seems to be where the error is occurring. It looks like one of your observations might be a spec, i.e. specs.DiscreteArray ,  as opposed to an actual numpy array or tensor.

**Comment by mmorris44** [comment]
@MohibAzam I'm closing this issue for now. I hope @KaleabTessera's comment solved your issue. Please feel free to open another if you're still having problems.
