### ISSUE TITLE
TypeError when using MAPPO with custom environment

### ISSUE THREAD

**Issue by dewet99** [instadeepai/Mava#553]
Hi there,

I'm attempting to integrate Mava into my project, and I'm running into some problems.
I've created a custom environment in Unity using their MLAgents package, and I wrote a wrapper for it based on Mava's PettingZooParallelEnvWrapper. When using your [mappo example](https://github.com/instadeepai/Mava/blob/develop/examples/tf/petting_zoo/butterfly/cooperative_pong/feedforward/decentralised/run_mappo.py) with my custom environment, everything starts up fine, the agents start taking actions but after a few seconds I receive the error below.

The environment returns observations as float32 arrays, and in the wrapper's `observation_spec()` it's also defined as float32.

Any ideas what might be causing this? Thank you in advance.

```
[evaluator/0] Traceback (most recent call last):
[evaluator/0]   File "/home/hebrect/Documents/DeWet/Unity Projects/portals-urp-main/Python/MLAgents_Portal/lib/python3.8/site-packages/launchpad/nodes/python/process_entry.py", line 110, in <module>
[evaluator/0]     app.run(main)
[evaluator/0]   File "/home/hebrect/Documents/DeWet/Unity Projects/portals-urp-main/Python/MLAgents_Portal/lib/python3.8/site-packages/absl/app.py", line 312, in run
[evaluator/0]     _run_main(main, args)
[evaluator/0]   File "/home/hebrect/Documents/DeWet/Unity Projects/portals-urp-main/Python/MLAgents_Portal/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
[evaluator/0]     sys.exit(main(argv))
[evaluator/0]   File "/home/hebrect/Documents/DeWet/Unity Projects/portals-urp-main/Python/MLAgents_Portal/lib/python3.8/site-packages/launchpad/nodes/python/process_entry.py", line 105, in main
[evaluator/0]     functions[task_id]()
[evaluator/0]   File "/home/hebrect/Documents/DeWet/Unity Projects/portals-urp-main/Python/MLAgents_Portal/lib/python3.8/site-packages/launchpad/nodes/python/node.py", line 72, in _construct_function
[evaluator/0]     return functools.partial(self._function, *args, **kwargs)()
[evaluator/0]   File "/home/hebrect/Documents/DeWet/Unity Projects/portals-urp-main/Python/MLAgents_Portal/lib/python3.8/site-packages/launchpad/nodes/courier/node.py", line 124, in run
[evaluator/0]     instance.run()
[evaluator/0]   File "/home/hebrect/Documents/DeWet/Unity Projects/portals-urp-main/Python/MLAgents_Portal/lib/python3.8/site-packages/mava/environment_loop.py", line 582, in run
[evaluator/0]     result = self.run_episode()
[evaluator/0]   File "/home/hebrect/Documents/DeWet/Unity Projects/portals-urp-main/Python/MLAgents_Portal/lib/python3.8/site-packages/mava/environment_loop.py", line 447, in run_episode
[evaluator/0]     actions = self._get_actions(timestep)
[evaluator/0]   File "/home/hebrect/Documents/DeWet/Unity Projects/portals-urp-main/Python/MLAgents_Portal/lib/python3.8/site-packages/mava/environment_loop.py", line 362, in _get_actions
[evaluator/0]     return self._executor.select_actions(timestep.observation)
[evaluator/0]   File "/home/hebrect/Documents/DeWet/Unity Projects/portals-urp-main/Python/MLAgents_Portal/lib/python3.8/site-packages/mava/systems/tf/mappo/execution.py", line 176, in select_actions
[evaluator/0]     actions, log_probs = self._select_actions(observations)
[evaluator/0]   File "/home/hebrect/Documents/DeWet/Unity Projects/portals-urp-main/Python/MLAgents_Portal/lib/python3.8/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
[evaluator/0]     raise e.with_traceback(filtered_tb) from None
[evaluator/0]   File "/home/hebrect/Documents/DeWet/Unity Projects/portals-urp-main/Python/MLAgents_Portal/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 1129, in autograph_handler
[evaluator/0]     raise e.ag_error_metadata.to_exception(e)
[evaluator/0] TypeError: in user code:
[evaluator/0] 
[evaluator/0]     File "/home/hebrect/Documents/DeWet/Unity Projects/portals-urp-main/Python/MLAgents_Portal/lib/python3.8/site-packages/mava/systems/tf/mappo/execution.py", line 159, in _select_actions  *
[evaluator/0]         action, log_prob = self._policy(agent, observation)
[evaluator/0]     File "/home/hebrect/Documents/DeWet/Unity Projects/portals-urp-main/Python/MLAgents_Portal/lib/python3.8/site-packages/mava/systems/tf/mappo/execution.py", line 123, in _policy  *
[evaluator/0]         policy = self._policy_networks[agent_key](batched_observation)
[evaluator/0]     File "/home/hebrect/Documents/DeWet/Unity Projects/portals-urp-main/Python/MLAgents_Portal/lib/python3.8/site-packages/sonnet/src/utils.py", line 70, in _decorate_unbound_method  *
[evaluator/0]         return decorator_fn(bound_method, self, args, kwargs)
[evaluator/0]     File "/home/hebrect/Documents/DeWet/Unity Projects/portals-urp-main/Python/MLAgents_Portal/lib/python3.8/site-packages/sonnet/src/base.py", line 272, in wrap_with_name_scope  *
[evaluator/0]         return method(*args, **kwargs)
[evaluator/0]     File "/home/hebrect/Documents/DeWet/Unity Projects/portals-urp-main/Python/MLAgents_Portal/lib/python3.8/site-packages/sonnet/src/sequential.py", line 72, in __call__  *
[evaluator/0]         outputs = mod(outputs, *args, **kwargs)
[evaluator/0]     File "/home/hebrect/Documents/DeWet/Unity Projects/portals-urp-main/Python/MLAgents_Portal/lib/python3.8/site-packages/sonnet/src/utils.py", line 70, in _decorate_unbound_method  *
[evaluator/0]         return decorator_fn(bound_method, self, args, kwargs)
[evaluator/0]     File "/home/hebrect/Documents/DeWet/Unity Projects/portals-urp-main/Python/MLAgents_Portal/lib/python3.8/site-packages/sonnet/src/base.py", line 272, in wrap_with_name_scope  *
[evaluator/0]         return method(*args, **kwargs)
[evaluator/0]     File "/home/hebrect/Documents/DeWet/Unity Projects/portals-urp-main/Python/MLAgents_Portal/lib/python3.8/site-packages/sonnet/src/sequential.py", line 72, in __call__  *
[evaluator/0]         outputs = mod(outputs, *args, **kwargs)
[evaluator/0]     File "/home/hebrect/Documents/DeWet/Unity Projects/portals-urp-main/Python/MLAgents_Portal/lib/python3.8/site-packages/sonnet/src/utils.py", line 70, in _decorate_unbound_method  *
[evaluator/0]         return decorator_fn(bound_method, self, args, kwargs)
[evaluator/0]     File "/home/hebrect/Documents/DeWet/Unity Projects/portals-urp-main/Python/MLAgents_Portal/lib/python3.8/site-packages/sonnet/src/base.py", line 272, in wrap_with_name_scope  *
[evaluator/0]         return method(*args, **kwargs)
[evaluator/0]     File "/home/hebrect/Documents/DeWet/Unity Projects/portals-urp-main/Python/MLAgents_Portal/lib/python3.8/site-packages/mava/components/tf/networks/continuous.py", line 117, in __call__  *
[evaluator/0]         return self._network(tf2_utils.batch_concat(observations))
[evaluator/0]     File "/home/hebrect/Documents/DeWet/Unity Projects/portals-urp-main/Python/MLAgents_Portal/lib/python3.8/site-packages/sonnet/src/utils.py", line 70, in _decorate_unbound_method  *
[evaluator/0]         return decorator_fn(bound_method, self, args, kwargs)
[evaluator/0]     File "/home/hebrect/Documents/DeWet/Unity Projects/portals-urp-main/Python/MLAgents_Portal/lib/python3.8/site-packages/sonnet/src/base.py", line 272, in wrap_with_name_scope  *
[evaluator/0]         return method(*args, **kwargs)
[evaluator/0]     File "/home/hebrect/Documents/DeWet/Unity Projects/portals-urp-main/Python/MLAgents_Portal/lib/python3.8/site-packages/sonnet/src/sequential.py", line 72, in __call__  *
[evaluator/0]         outputs = mod(outputs, *args, **kwargs)
[evaluator/0]     File "/home/hebrect/Documents/DeWet/Unity Projects/portals-urp-main/Python/MLAgents_Portal/lib/python3.8/site-packages/sonnet/src/utils.py", line 70, in _decorate_unbound_method  *
[evaluator/0]         return decorator_fn(bound_method, self, args, kwargs)
[evaluator/0]     File "/home/hebrect/Documents/DeWet/Unity Projects/portals-urp-main/Python/MLAgents_Portal/lib/python3.8/site-packages/sonnet/src/base.py", line 272, in wrap_with_name_scope  *
[evaluator/0]         return method(*args, **kwargs)
[evaluator/0]     File "/home/hebrect/Documents/DeWet/Unity Projects/portals-urp-main/Python/MLAgents_Portal/lib/python3.8/site-packages/sonnet/src/linear.py", line 91, in __call__  *
[evaluator/0]         outputs = tf.matmul(inputs, self.w)
[evaluator/0] 
[evaluator/0]     TypeError: Input 'b' of 'MatMul' Op has type float32 that does not match type float64 of argument 'a'.
[evaluator/0]
```

**Comment by DriesSmit** [comment]
Are you using this [env_wrapper](https://github.com/instadeepai/Mava/blob/develop/examples/tf/petting_zoo/butterfly/cooperative_pong/feedforward/decentralised/run_mappo.py#L60)?

**Comment by DriesSmit** [comment]
@KaleabTessera have you seen this before?

**Comment by dewet99** [comment]
> Hey. Are you using this [env_wrapper](https://github.com/instadeepai/Mava/blob/develop/examples/tf/petting_zoo/butterfly/cooperative_pong/feedforward/decentralised/run_mappo.py#L60)?

No. I had to make a custom `make_environment` method and didn't include the `env_preprocess_wrappers`. To be honest, during wrapper implementation I couldn't 100% wrap my mind around what exactly that does. Added to that, Unity' MLAgents package and its PythonAPI aren't very compatible with PettingZoo, the wrapper I created was essentially made from scratch.

**Comment by dewet99** [comment]
I've found the issue. 
Unity returns a decision_step object that contains all the agents that require an action at that step. This is how I access each agent's observations. In my environment, there are two agents. Sometimes, only one agent will require an action, which means that only one agent has an observation available. Mava requires obervations for both agents, so in the cases where there aren't any observations available, I generate an empty observation. I did not assign a dtype for this observation, so it defaulted to float64. When I converted it to float32, it solved the error.

**Comment by DriesSmit** [comment]
Glad you figure it out :+1:
