### ISSUE TITLE
ValueError: Unable to create item in table 'trainer' since the provided trajectory is inconsistent with the table signature.

### ISSUE THREAD

**Issue by dewet99** [instadeepai/Mava#554]
Hi there,

I'm receiving a value error (see below) when running the mappo example with a custom environment and a wrapper. It seems to be an action shape mismatch, but I can't seem to find the origin.

The wrapped environment has an `action spec` as follows:
```
{'agent_0': BoundedArray(shape=(1, 4), dtype=dtype('float32'), name='portalPOCA?team=0', minimum=[[0. 0. 0. 0.]], maximum=[[4. 2. 2. 2.]]), 'agent_1': BoundedArray(shape=(1, 4), dtype=dtype('float32'), name='portalPOCA?team=0', minimum=[[0. 0. 0. 0.]], maximum=[[4. 2. 2. 2.]])}
```
However, when I run the example with my environment and print the shape of the actions passed to the `step` function, it returns a shape of `(4,)` for each action, which is where I think the error stems from. According to dm_env [documentation](https://github.com/deepmind/dm_env/blob/master/dm_env/_environment.py#:~:text=Args%3A,corresponding%20to%20%60action_spec()%60.), these actions should have the format specified in `action_spec`, but it doesn't. Any ideas why this might be, and if it is the cause of the ValueError?

Any help would be appreciated, and thank you in advance.

```
[executor/0] Traceback (most recent call last):
[executor/0]   File "/home/hebrect/Documents/DeWet/Unity Projects/portals-urp-main/Python/MLAgents_Portal/lib/python3.8/site-packages/launchpad/nodes/python/process_entry.py", line 110, in <module>
[executor/0]     app.run(main)
[executor/0]   File "/home/hebrect/Documents/DeWet/Unity Projects/portals-urp-main/Python/MLAgents_Portal/lib/python3.8/site-packages/absl/app.py", line 312, in run
[executor/0]     _run_main(main, args)
[executor/0]   File "/home/hebrect/Documents/DeWet/Unity Projects/portals-urp-main/Python/MLAgents_Portal/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
[executor/0]     sys.exit(main(argv))
[executor/0]   File "/home/hebrect/Documents/DeWet/Unity Projects/portals-urp-main/Python/MLAgents_Portal/lib/python3.8/site-packages/launchpad/nodes/python/process_entry.py", line 105, in main
[executor/0]     functions[task_id]()
[executor/0]   File "/home/hebrect/Documents/DeWet/Unity Projects/portals-urp-main/Python/MLAgents_Portal/lib/python3.8/site-packages/launchpad/nodes/python/node.py", line 72, in _construct_function
[executor/0]     return functools.partial(self._function, *args, **kwargs)()
[executor/0]   File "/home/hebrect/Documents/DeWet/Unity Projects/portals-urp-main/Python/MLAgents_Portal/lib/python3.8/site-packages/launchpad/nodes/courier/node.py", line 124, in run
[executor/0]     instance.run()
[executor/0]   File "/home/hebrect/Documents/DeWet/Unity Projects/portals-urp-main/Python/MLAgents_Portal/lib/python3.8/site-packages/mava/environment_loop.py", line 582, in run
[executor/0]     result = self.run_episode()
[executor/0]   File "/home/hebrect/Documents/DeWet/Unity Projects/portals-urp-main/Python/MLAgents_Portal/lib/python3.8/site-packages/mava/environment_loop.py", line 466, in run_episode
[executor/0]     self._executor.observe(
[executor/0]   File "/home/hebrect/Documents/DeWet/Unity Projects/portals-urp-main/Python/MLAgents_Portal/lib/python3.8/site-packages/mava/systems/tf/mappo/execution.py", line 234, in observe
[executor/0]     self._adder.add(adder_actions, next_timestep, next_extras)  # type: ignore
[executor/0]   File "/home/hebrect/Documents/DeWet/Unity Projects/portals-urp-main/Python/MLAgents_Portal/lib/python3.8/site-packages/mava/adders/reverb/base.py", line 427, in add
[executor/0]     self._write()
[executor/0]   File "/home/hebrect/Documents/DeWet/Unity Projects/portals-urp-main/Python/MLAgents_Portal/lib/python3.8/site-packages/acme/adders/reverb/sequence.py", line 177, in _write
[executor/0]     self._maybe_create_item(self._sequence_length)
[executor/0]   File "/home/hebrect/Documents/DeWet/Unity Projects/portals-urp-main/Python/MLAgents_Portal/lib/python3.8/site-packages/mava/adders/reverb/sequence.py", line 135, in _maybe_create_item
[executor/0]     self.write_experience_to_tables(trajectory, table_priorities)
[executor/0]   File "/home/hebrect/Documents/DeWet/Unity Projects/portals-urp-main/Python/MLAgents_Portal/lib/python3.8/site-packages/mava/adders/reverb/base.py", line 347, in write_experience_to_tables
[executor/0]     self._writer.create_item(
[executor/0]   File "/home/hebrect/Documents/DeWet/Unity Projects/portals-urp-main/Python/MLAgents_Portal/lib/python3.8/site-packages/reverb/trajectory_writer.py", line 352, in create_item
[executor/0]     self._writer.CreateItem(table, priority,
[executor/0] ValueError: Unable to create item in table 'trainer' since the provided trajectory is inconsistent with the table signature. The table expects column 6 to be a float [11,1,4] tensor but got a float [11,4] tensor.
[executor/0] 
[executor/0] The table signature is:
[executor/0] 	0: Tensor<name: 'observations/agent_0/observation/0/agent_0/observation', dtype: float, shape: [11,84,84,3]>, 1: Tensor<name: 'observations/agent_0/legal_actions/0/agent_0/legal_actions', dtype: float, shape: [11,1,4]>, 2: Tensor<name: 'observations/agent_0/terminal/0/agent_0/terminal', dtype: float, shape: [11,1]>, 3: Tensor<name: 'observations/agent_1/observation/0/agent_1/observation', dtype: float, shape: [11,84,84,3]>, 4: Tensor<name: 'observations/agent_1/legal_actions/0/agent_1/legal_actions', dtype: float, shape: [11,1,4]>, 5: Tensor<name: 'observations/agent_1/terminal/0/agent_1/terminal', dtype: float, shape: [11,1]>, 6: Tensor<name: 'actions/agent_0/actions/1/agent_0/actions', dtype: float, shape: [11,1,4]>, 7: Tensor<name: 'actions/agent_0/log_probs/1/agent_0/log_probs', dtype: float, shape: [11]>, 8: Tensor<name: 'actions/agent_1/actions/1/agent_1/actions', dtype: float, shape: [11,1,4]>, 9: Tensor<name: 'actions/agent_1/log_probs/1/agent_1/log_probs', dtype: float, shape: [11]>, 10: Tensor<name: 'rewards/agent_0/2/agent_0', dtype: float, shape: [11]>, 11: Tensor<name: 'rewards/agent_1/2/agent_1', dtype: float, shape: [11]>, 12: Tensor<name: 'discounts/agent_0/3/agent_0', dtype: float, shape: [11]>, 13: Tensor<name: 'discounts/agent_1/3/agent_1', dtype: float, shape: [11]>, 14: Tensor<name: 'start_of_episode/4', dtype: bool, shape: [11]>, 15: Tensor<name: 'extras/network_keys/agent_0/5/network_keys/agent_0', dtype: int32, shape: [11]>, 16: Tensor<name: 'extras/network_keys/agent_1/5/network_keys/agent_1', dtype: int32, shape: [11]>
[executor/0] 
[executor/0] The provided trajectory signature is:
[executor/0] 	0: Tensor<name: '0', dtype: float, shape: [11,84,84,3]>, 1: Tensor<name: '1', dtype: float, shape: [11,1,4]>, 2: Tensor<name: '2', dtype: float, shape: [11,1]>, 3: Tensor<name: '3', dtype: float, shape: [11,84,84,3]>, 4: Tensor<name: '4', dtype: float, shape: [11,1,4]>, 5: Tensor<name: '5', dtype: float, shape: [11,1]>, 6: Tensor<name: '6', dtype: float, shape: [11,4]>, 7: Tensor<name: '7', dtype: float, shape: [11]>, 8: Tensor<name: '8', dtype: float, shape: [11,4]>, 9: Tensor<name: '9', dtype: float, shape: [11]>, 10: Tensor<name: '10', dtype: float, shape: [11]>, 11: Tensor<name: '11', dtype: float, shape: [11]>, 12: Tensor<name: '12', dtype: float, shape: [11]>, 13: Tensor<name: '13', dtype: float, shape: [11]>, 14: Tensor<name: '14', dtype: bool, shape: [11]>, 15: Tensor<name: '15', dtype: int32, shape: [11]>, 16: Tensor<name: '16', dtype: int32, shape: [11]>.
[executor/0]
```

**Comment by dewet99** [comment]
> If you change the action_spec shape to (4,) does it help? You would probably need to either update the spec or update your environment action shape. So maybe try to update the spec first.

That was the issue. So simple. I had it as (4,) originally but when passing the (4,) actions to Unity it threw an error, because Unity requires (1,4) shape. So I modified the wrapper to reshape the (4,) to (1,4) when passing the actions to the environment, but I also changed action spec to reflect that change, which I shouldn't have done.

Thank you.
